version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./init.sql:/data/application/init.sql
    command:
      - --init-file
      - /data/application/init.sql
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci